[[bond]]
source = "tpknam1qrxt6cnrwmj3ungupqjnyck6yvq698alsezgznfsm4fzp3dg7j38vc55xd2"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "1000"

[bond.signatures]
tpknam1qrxt6cnrwmj3ungupqjnyck6yvq698alsezgznfsm4fzp3dg7j38vc55xd2 = "signam1qqj6ezphw3nrj7lkauel9ppw337hwqesl8q9kjnm5ktvy5p4tqmupd754s0ny9vmkux5klj7kpvr06trgumusyxdczeg65py3pu663qr3hzhea"


[[bond]]
source = "tpknam1qrxt6cnrwmj3ungupqjnyck6yvq698alsezgznfsm4fzp3dg7j38vc55xd2"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "250"

[bond.signatures]
tpknam1qrxt6cnrwmj3ungupqjnyck6yvq698alsezgznfsm4fzp3dg7j38vc55xd2 = "signam1qpsqh7v59y730kg9zlm3u4l994q30zr45yp9jppy90xfvrx5hl7e77tqr68kwyum4j2g7juq5lv99j8xxuhtyp40a0ppr24977c8hvq2ky0xur"
